image:
  file: Dockerfile

workspaceLocation: canvas/.workspace.json
checkoutLocation: canvas

github:
  prebuilds:
    # Enable for the master/default branch (defaults to true)
    master: false
    # Enable for all branches in this repo (defaults to false)
    branches: true
    # Enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # Enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # Add a check to pull requests (defaults to true)
    addCheck: true
    # Add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # Add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # Add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

tasks:
  - init: |
      # Initializing the Laravel app

      # Reload the .bash_profile to utilize composer-link()
      source ~/.bash_profile

      cd /workspace

      # Create a new Laravel app
      composer create-project --prefer-dist laravel/laravel laravel

      cd /workspace/laravel

      # Create a new database
      touch database/database.sqlite

      # Update the .env database configuration
      sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env
      sed -i 's/DB_DATABASE=laravel/#DB_DATABASE=laravel/g' .env

      # Link Canvas to the Laravel app
      composer-link ../canvas/
      composer require austintoddj/canvas @dev

      # Install Canvas
      php artisan canvas:install
      php artisan storage:link

      # Remove existing assets from the Laravel app
      rm -rf public/vendor/canvas/*

      # Create a symlink to the package assets
      cd public/vendor/canvas
      ln -s ../../../../canvas/public/* .

      cd /workspace/laravel

      # Trust any proxy in a chain of proxies
      php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"
      sed -Ei "s|'proxies' => null|'proxies' => '**'|g" config/trustedproxy.php

    command: |
      cd /workspace/laravel

      # Define base app URL
      export url=$(gp url 8000); sed -Ei "s|APP_URL=http://localhost|APP_URL=${url}|g" .env

      # Define asset path
      export url=$(gp url 8000); sed -Ei "1i\ASSET_URL=${url}" .env

      # Clear and cache the app configuration
      php artisan config:clear
      php artisan cache:clear
      php artisan config:cache

      # Serve the Laravel app
      php artisan serve

  - init: |
      # Initializing the Canvas package

      # Install core PHP dependencies
      composer install

      # Install core JS dependencies
      yarn

    command: |
      yarn watch

    openMode: split-right

ports:
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: notify
